from http import HTTPStatus

STATUS_OK = HTTPStatus.OK
STATUS_FORBIDDEN = HTTPStatus.FORBIDDEN
STATUS_NOT_FOUND = HTTPStatus.NOT_FOUND
STATUS_INTERNAL_ERROR = HTTPStatus.INTERNAL_SERVER_ERROR
STATUS_UNAVAILABLE = HTTPStatus.SERVICE_UNAVAILABLE

STATUS_DESCRIPTIONS = {
    STATUS_OK: "Успешный запрос",
    STATUS_FORBIDDEN: "Доступ запрещен",
    STATUS_NOT_FOUND: "Фандом не найден"
}
